-- Driver profile: license, address, emergency contact and editable fields.
ALTER TABLE drivers ADD COLUMN license_number VARCHAR(60),
 ADD COLUMN license_state VARCHAR(2),
 ADD COLUMN license_expiry DATE,
 ADD COLUMN date_of_birth DATE,
 ADD COLUMN address_line1 VARCHAR(200),
 ADD COLUMN address_line2 VARCHAR(200),
 ADD COLUMN address_city VARCHAR(100),
 ADD COLUMN address_state VARCHAR(40),
 ADD COLUMN address_postal_code VARCHAR(20),
 ADD COLUMN address_country_code CHAR(2) NOT NULL DEFAULT 'US',
 ADD COLUMN emergency_contact_name VARCHAR(160),
 ADD COLUMN emergency_contact_phone VARCHAR(20),
 ADD COLUMN vehicle_make VARCHAR(60),
 ADD COLUMN vehicle_model VARCHAR(60),
 ADD COLUMN vehicle_year INT,
 ADD COLUMN vehicle_color VARCHAR(30),
 ADD COLUMN insurance_reference VARCHAR(100),
 ADD COLUMN notes TEXT,
 ADD COLUMN updated_at TIMESTAMPTZ;
