-- Terminal452-compatible cabinet-scoped admin code roster.
-- No default passwords. Provision existing authorized records separately.
CREATE TABLE cabinet_admin_card (
 card_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 cabinet_id BIGINT NOT NULL REFERENCES cabinet(cabinet_id),
 rfid VARCHAR(64) NOT NULL CHECK(length(trim(rfid)) BETWEEN 1 AND 64),
 zp_admin_id VARCHAR(64) NOT NULL,
 zp_admin_name VARCHAR(120) NOT NULL DEFAULT '',
 zp_admin_role VARCHAR(40) NOT NULL DEFAULT 'Admin',
 status SMALLINT NOT NULL DEFAULT 1 CHECK(status IN (0,1)),
 create_time TIMESTAMPTZ NOT NULL DEFAULT now(),
 update_time TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX cabinet_admin_card_code ON cabinet_admin_card(cabinet_id,lower(trim(rfid)));
-- The terminal API may read the roster, never provision or change authority.
GRANT SELECT ON cabinet_admin_card TO zpx_runtime;
